base: &base
  image: "golang:1.20"
  caches: &base_caches
    - name: gomodcache
      path: /cache
  env: &base_env
    - key: GOMODCACHE
      value: /cache
    - key: GITHUB_TOKEN
      valueFrom: GITHUB_TOKEN
  mounts: &base_mounts
    - host: .
      container: /src
  workdir: /src

# TODO: Implement
#secretEngines:
#  - name: vault
#    type: Vault
#    spec:
#      host: https://vault.opslevel.com
#      token: ${VAULT_TOKEN}
#      namespace: dev

secrets:
  - name: GITHUB_TOKEN
    from: env
  - name: MYSQL_PASSWORD
    from: vault
    spec:
      path: /secrets/mysql/password

services:
  - name: redis
    image: redis:7.0
    ports:
      - port: 6379
        protocol: TCP

pipeline:
  - name: "test"
    <<: *base
    commands:
      - go test ./...
  - name: "build"
    <<: *base
    commands:
      - go build -o ./cli .
      - chmod +x ./cli
      - ./cli -h
  - name: "integration"
    image: redis:7.0
    services:
      db: redis
    commands:
      - redis-cli -h db -p 6379 ping
