base: &base
  image: "golang:1.20"
  caches: &base_caches
    - name: gomodcache
      path: /cache
  env: &base_env
    - key: GOMODCACHE
      value: /cache
  mounts: &base_mounts
    - host: .
      container: /workspace
  workdir: &base_workdir /workspace

pipeline:
  - name: Run Tests
    <<: *base
    commands:
      - go mod tidy
      - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
    artifacts:
      - name: Coverage
        path: coverage.txt
  - name: Upload Coverage
    image: debian:bullseye
    mounts:
      - host: .
        container: /workspace
    workdir: /workspace
    dependencies:
      - name: Coverage
        path: ./tmp/coverage.txt
    commands:
      - apt-get update -y
      - apt-get install -y curl git
      - curl -Os https://uploader.codecov.io/latest/linux/codecov
      - chmod +x codecov
      - ./codecov -R /workspace -B $(git branch --show-current) -t 464532ed-1ff3-4c0e-a803-4b9f77004715 -f ./tmp/coverage.txt